version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/urlShortener

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
